-- Seed data for the Loan Picks Dashboard
-- Run this after applying supabase/schema.sql

INSERT INTO products (
  name,
  bank,
  type,
  rate_apr,
  min_income,
  min_credit_score,
  tenure_min_months,
  tenure_max_months,
  processing_fee_pct,
  prepayment_allowed,
  disbursal_speed,
  docs_level,
  summary,
  faq,
  terms
) VALUES
  (
    'Flexi Personal Loan',
    'Axis Bank',
    'personal',
    13.5,
    30000,
    700,
    12,
    60,
    1.5,
    TRUE,
    'fast',
    'standard',
    'Flexible personal loan for salaried professionals with quick approval.',
    '[{"question":"Is part-prepayment allowed?","answer":"Yes, you can prepay after 6 EMIs without penalty."}]'::jsonb,
    '{"segment":"salaried","city_tier":"1"}'::jsonb
  ),
  (
    'EduAdvance Student Loan',
    'HDFC Bank',
    'education',
    11.9,
    0,
    680,
    24,
    84,
    2.0,
    TRUE,
    'standard',
    'standard',
    'Education loan aimed at higher studies in India and abroad.',
    '[{"question":"Is a co-borrower required?","answer":"Yes, a parent or guardian is required as co-borrower."}]'::jsonb,
    '{"max_loan_amount":1500000}'::jsonb
  ),
  (
    'HomePlus Housing Loan',
    'ICICI Bank',
    'home',
    8.35,
    50000,
    720,
    60,
    360,
    0.75,
    TRUE,
    'standard',
    'standard',
    'Long-term home loan with competitive interest rates and balance transfer facility.',
    '[{"question":"Is top-up loan available?","answer":"Top-up is available after 12 months of timely repayments."}]'::jsonb,
    '{"max_ltv_pct":80}'::jsonb
  ),
  (
    'DriveEasy Car Loan',
    'SBI',
    'vehicle',
    9.25,
    25000,
    680,
    12,
    84,
    0.5,
    TRUE,
    'fast',
    'standard',
    'Vehicle loan for new cars with low processing fee and quick disbursal.',
    '[{"question":"Is used car financing allowed?","answer":"Used cars up to 5 years old are eligible."}]'::jsonb,
    '{"max_vehicle_age_years":5}'::jsonb
  ),
  (
    'SmartLine Credit',
    'Kotak Mahindra Bank',
    'credit_line',
    16.9,
    40000,
    710,
    6,
    48,
    2.0,
    TRUE,
    'fast',
    'low',
    'Flexible personal line of credit for short-term cash needs.',
    '[{"question":"How is interest calculated?","answer":"Interest is charged only on the utilized amount on a daily basis."}]'::jsonb,
    '{"min_draw_amount":5000}'::jsonb
  ),
  (
    'Consolidate+ Loan',
    'Axis Bank',
    'debt_consolidation',
    14.25,
    35000,
    690,
    12,
    72,
    1.25,
    TRUE,
    'standard',
    'standard',
    'Debt consolidation loan to combine multiple credit cards and loans.',
    '[{"question":"Are credit card closures mandatory?","answer":"Yes, high-interest credit cards must be closed at disbursal."}]'::jsonb,
    '{"allowed_obligations":["credit_cards","personal_loans"]}'::jsonb
  ),
  (
    'QuickCash Instant Loan',
    'HDFC Bank',
    'personal',
    19.5,
    20000,
    650,
    6,
    24,
    2.5,
    TRUE,
    'fast',
    'low',
    'Instant small-ticket personal loan disbursed within minutes for eligible customers.',
    '[{"question":"Is income proof required?","answer":"For pre-approved customers, minimal documentation is required."}]'::jsonb,
    '{"max_amount":200000}'::jsonb
  ),
  (
    'SecureHome Loan',
    'SBI',
    'home',
    8.75,
    60000,
    730,
    84,
    300,
    0.5,
    TRUE,
    'standard',
    'high',
    'Home loan tailored for first-time home buyers with conservative underwriting.',
    '[{"question":"Is property insurance mandatory?","answer":"Yes, property insurance for the loan tenure is mandatory."}]'::jsonb,
    '{"processing_time_days":7}'::jsonb
  ),
  (
    'StudyNow Overseas Loan',
    'Axis Bank',
    'education',
    12.75,
    0,
    700,
    36,
    120,
    2.25,
    TRUE,
    'standard',
    'standard',
    'Education loan focused on overseas programs with extended moratorium.',
    '[{"question":"Is there a repayment holiday?","answer":"Repayment starts 6 months after course completion."}]'::jsonb,
    '{"moratorium_months":6}'::jsonb
  ),
  (
    'RideOn Two-Wheeler Loan',
    'Kotak Mahindra Bank',
    'vehicle',
    10.5,
    18000,
    640,
    6,
    36,
    1.0,
    TRUE,
    'fast',
    'low',
    'Two-wheeler loan with low documentation requirements for salaried and self-employed.',
    '[{"question":"Is zero down payment available?","answer":"Zero down payment is available for select models and profiles."}]'::jsonb,
    '{"max_ltv_pct":95}'::jsonb
  );

